# Generated by Django 6.0.5 on 2026-05-21 22:26

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('vin_number', models.CharField(max_length=17, unique=True, validators=[store.models.validate_vin])),
                ('year', models.PositiveIntegerField(validators=[store.models.validate_car_year])),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('license_expiration_date', models.DateField()),
                ('date_of_birth', models.DateField(validators=[store.models.validate_client_age])),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Car Showroom', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('stock_number_mode', models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')], default=1)),
                ('stock_number_start_value', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[store.models.validate_positive_price])),
                ('date', models.DateField(validators=[store.models.validate_not_future_date])),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='store.carinventory')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[store.models.validate_positive_price])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale_record', to='store.carinventory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='store.client')),
            ],
        ),
    ]
